#Pick the sprite used for highlighting the currently selected item in item content tooltips.
#Default Value: HIGHLIGHT
#Allowed Values: SELECTION, HIGHLIGHT
item_storage_highlight_sprite = "HIGHLIGHT"
#Show an plus sign indicator on container items when the item stack held by the cursor can be added.
#Default Value: true
item_storage_indicator = true
#Color item inventories on tooltips according to the container item's color.
#Default Value: true
item_storage_colors = true
#Show a bar on container items indicating the current fill level.
#Default Value: false
override_item_storage_bar = false
#Select a modifier key required to be held to use single item movement when enabled in the server config.
#Default Value: CONTROL_OR_COMMAND
#Allowed Values: ALWAYS, NEVER, SHIFT, CONTROL, CONTROL_OR_COMMAND, ALT
single_item_movement = "CONTROL_OR_COMMAND"
#Control the mouse button mappings when moving item contents.
#The split scheme mirrors vanilla's bundle mechanics, while the single scheme maps everything to the right mouse button; providing more overall flexibility.
#Default Value: SINGLE_INPUT
#Allowed Values: SPLIT_INPUT, SINGLE_INPUT
control_scheme = "SINGLE_INPUT"
#Show the item tooltip for the item currently held by the cursor to allow for scrolling through it.
#Select a modifier key required to be held, otherwise selecting "KEY" serves as a toggle. The key mapping is defined in vanilla's controls menu.
#Default Value: ALT
#Allowed Values: ALWAYS, NEVER, SHIFT, CONTROL, CONTROL_OR_COMMAND, ALT, KEY
item_held_by_cursor_tooltip = "ALT"
#Expand item tooltips to show their contents.
#Select a modifier key required to be held, otherwise selecting "KEY" serves as a toggle. The key mapping is defined in vanilla's controls menu.
#Default Value: ALWAYS
#Allowed Values: ALWAYS, NEVER, SHIFT, CONTROL, CONTROL_OR_COMMAND, ALT, KEY
item_storage_tooltip = "ALWAYS"
#Allow navigating nested storage item contents by pressing any selection key while the respective item is highlighted on the current tooltip. Use backspace to go back to the previous storage item contents.
#Contents are only shown visually; they cannot be interacted with.
#Default Value: true
nested_item_tooltips = true
#Scroll vertically through contents shown on an item's tooltip. Otherwise, scrolling only works in horizontal directions.
#Select a modifier key required to be held to use vertical scrolling.
#Default Value: SHIFT
#Allowed Values: ALWAYS, NEVER, SHIFT, CONTROL, CONTROL_OR_COMMAND, ALT
vertical_tooltip_scrolling = "SHIFT"
#Invert scroll wheel direction for moving items with a container item for single item movement.
#Default Value: false
reverse_single_item_scrolling = false
