name = "ERDM-Official"
author = "Samukis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "140ff9db4d16241af3a6357ad035daed25b6e8359bdc7795d0e17ac668e91b8b"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
