name = "ERDM-Official"
author = "Samukis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33e33b212e6af41970c919f7e22a134430774f3a1f43bc3fbc98e5870e6df24d"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
