name = "ERDM-Official"
author = "Samukis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ae9719e5efb39a28e9536c26a548c0e8ba0163846dc7626a452c909471653ca"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
