mute-on-alt-tab: false
default-render-distance: 96
default-default-display-volume: 0.5
displays-enabled: true
ytdlp-cookies-from-browser: none
ytdlp-proxy: ''
use-hw-accel: true
unshaded-displays: true
audio-acoustics: advanced
audio-output-profile: headphones
